---
swagger: '2.0'
info:
  title: CRM
  description: CRM Description Placeholder
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
paths:
  "/users/{user_id}/contacts/{id}":
    get:
      summary: Provides all the data about specific contact ID provided in the endpoint
      tags:
      - Contact
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      - name: id
        in: path
        required: true
      responses:
        '200':
          description: ''
    patch:
      summary: Allows user to update its basic information. Only include the fields
        you want to update.
      tags:
      - Contact
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      - name: id
        in: path
        required: true
      - name: contact
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              format: string
            phone_number:
              format: string
      responses:
        '200':
          description: update successful
        '422':
          description: Unprocessable Entity
  "/users/{user_id}/contacts":
    post:
      summary: Allows for a contact to be created under the user account found within
        the authorization credentials
      tags:
      - Contact
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              properties:
                name:
                  type: string
                email:
                  format: string
                phone_number:
                  format: string
      responses:
        '200':
          description: contact created successfully
        '422':
          description: Unprocessable Entity
  "/login":
    post:
      summary: |-
        Upon successful login this endpoint returns an object with the user's basic account info along with
               a bearer token in its response header. Use the bearer token for all future requests during that login session
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              properties:
                email:
                  type: string
                password:
                  format: string
          required:
          - email
          - password
      responses:
        '200':
          description: Logged in sucessfully.
        '401':
          description: Invalid username or password. Please check your spelling and
            cases or reset your password
        '404':
          description: No account found with email <USER EMAIL>. Please signup a new
            account to log in
        '403':
          description: Unauthorized request. Check your authorization credentials
  "/logout":
    delete:
      summary: Logs a user out of their current session
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      responses:
        '200':
          description: Logged out sucessfully
        '401':
          description: Couldn't find an active session.
  "/users/{id}":
    get:
      summary: Provides data on the User's basic account information and a list of
        all contacts logged in the database
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      responses:
        '200':
          description: ''
    patch:
      summary: Allows user to update its basic information. Only include the fields
        you want to update.
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
      - name: user
        in: body
        schema:
          type: object
          properties:
            user:
              properties:
                email:
                  type: string
                name:
                  format: string
                username:
                  format: string
      responses:
        '200':
          description: ''
